blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapi.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


blogapi/urls.py
from django.urls import path
from .views import *
from django.urls import reverse_lazy

LOGIN_URL = reverse_lazy('blog:login')

app_name = 'blog'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('new-post/', create_post, name='new-post'),   
    path('post/<int:pk>/', get_post, name='get-post'),   
    path('register/', register, name='register'),
    
    
]

blogapi/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class BlogPost(models.Model):
    body = models.TextField(null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    img_url = models.ImageField(upload_to='blog/img')
    subtitle = models.CharField(max_length=500)
    title = models.CharField(max_length=500, unique=True)
    author = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE, verbose_name='Blog Author')
    

    class Meta:
        db_table = 'BlogPost'


class Comment(models.Model):
    comment_author = models.ForeignKey(User, related_name='commenter', verbose_name='Comment Author', on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    blog_post = models.ForeignKey(
        BlogPost, related_name='comments', on_delete=models.CASCADE, verbose_name='Related Blog Post'
    )

    class Meta:
        db_table = 'Comment'
    


blogapi/views.py
# REST FRAMEWORK
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

# from .serializers import PostSerializer

# Just basic old full stack
from .models import *

from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseForbidden

from . utils import NotificationManager


from django_gravatar.helpers import get_gravatar_url




def is_admin(func):
    @login_required
    def wrapper(request, *args, **kwargs):
        if request.user.is_superuser:
            return func(request, *args, **kwargs)
        else:
            return HttpResponseForbidden("You do not have permission to access this route.")
    return wrapper



# @api_view(['GET', 'POST'])
# def allPosts(request):
#     if request.method == 'GET':
#         allpost = blogpost.objects.all()
#         serializer = PostSerializer(allpost, many=True)
#         return Response(serializer.data)


#     elif request.method == 'POST':
#         serializer = PostSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, satus=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# @api_view(['GET', 'PUT', 'DELETE'])
# def mypost(request, pk):
#     try:
#         getpost = blogpost.objects.get(pk=pk)
#     except blogpost.DoesNotExist:
#         return Response(status=status.HTTP_404_NOT_FOUND)
#     else:
#         if request.method == 'GET':
#             serializer = PostSerializer(getpost)
#             return Response(serializer.data)

#         elif request.method == 'PUT':
#             serializer = PostSerializer(getpost, data=request.data)
#             if serializer.is_valid():
#                 serializer.save()
#                 return Response(serializer.data)
#             return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
#         elif request.method == 'DELETE':
#             getpost.delete()
#             return Response(status=status.HTTP_200_SUCCESS)



def home(request):
    blogpost = BlogPost.objects.all()
    # day=current_day, month=current_month, year=current_year, feed=feed,current_user=current_user, logged_in=logged_in
    return render(request, "index.html", {'feed': blogpost})


def about(request):
    return render(request,"about.html")


def contact(request):
    global logged_in
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        msg = f"Name: {name}\nEmail: {email}\nPhone Number: {phone}\nMessage: {message}"
        notify = NotificationManager(msg=msg, recipient="imlearning862@gmail.com", subject="Blog Message")
        if notify:
            success_msg = "Successfully, sent your message."
            return render(request, "contact.html", {'success':True, 'success_msg': success_msg})
        else:
            return render(request,'error.html')
    return render(request, "contact.html", {'success': False})



@is_admin
def delete(request, pk):
    blogpost = BlogPost.objects.get(pk=pk)
    blogpost.delete()

    return redirect('/')


@login_required
def edit(request, pk):
    # Fetch the blog post or return a 404 if not found
    post = get_object_or_404(BlogPost, pk=pk)

    # Pre-fill data for the template
    data = {
        'title': post.title,
        'subtitle': post.subtitle,
        'img': request.build_absolute_uri(post.img_url.url) if post.img_url else None,
        'body': post.body,
        'blog': post
    }

    # Process POST request for updating the blog post
    if request.method == "POST":
        post.title = request.POST.get('title', post.title)
        post.subtitle = request.POST.get('subtitle', post.subtitle)
        post.body = request.POST.get('body', post.body)

        # Handle image upload if a new image is provided
        if 'img' in request.FILES:
            post.img_url = request.FILES['img']

        post.save()



        # Redirect to the blog post's detail page after updating
        return redirect('blog:get-post', pk=post.pk)

    # Render the edit form with the existing data
    return render(request, 'edit.html', data)



def login_user(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')


        try:
            user = User.objects.get(username=username)

        except User.DoesNotExist:
            error = "This email does not exist. Please try again."
            messages.error(request, error)
            return redirect('blog:login')
        else:
            if check_password(password, user.password):

                login(request, user)
                return redirect("blog:home")
            else:
                error = "Incorrect password. Please try again."
                redirect('blog:login')
    return render(request, "login.html")




def logout_user(request):
    logout(request)
    return redirect('blog:home')



@login_required
def create_post(request):
    if request.method == "POST":
        new_post = BlogPost(title=request.POST.get('title'),
                            subtitle=request.POST.get('subtitle'),
                            author=request.user,
                            img_url=request.FILES.get('img'),
                            body=request.POST.get('body'),
                            )
        try:
            new_post.save()
        except:
            # Handle unique constraint failure
            data  = {}
            data['error'] = "A blog post with this title already exists."
            return render(request, 'edit.html', data)

        return redirect("/")
    return render(request, "make-post.html")


def get_post(request, pk):
    feed = BlogPost.objects.get(pk=pk)

    # Fetch comments for the post
    comments = Comment.objects.filter(blog_post=feed)


    if request.method == 'POST':
        # Handle new comment submission
        comment_text = request.POST.get('comment')
        try:
            new_comment = Comment(comment_author=request.user, comment_text=comment_text, blog_post=feed)
        except:
            error = "Please Login and try again."
            messages.error(request, error)
            return redirect('blog:login')
        new_comment.save()
        return redirect('blog:get-post', pk=feed.pk)

    # Render the template
    return render(request, "post.html", {'feed': feed, 'comments': comments})


def register(request):
    if request.method == "POST":
        email = request.POST.get('email')
        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        password = request.POST.get('password')

        # Check if a user with the same email or username already exists
        if User.objects.filter(email=email).exists():
            error = 'Sorry, that email is already registered. Login instead.'
            return redirect('blog:login')

        if User.objects.filter(username=username).exists():
            error = 'Sorry, that username is already taken. Choose a different one.'
            return render(request, "register.html", {"error": error})

        # Create new user
        new_user = User.objects.create_user(
            username=username,
            email=email,
            password=password,
            first_name=firstname,
            last_name=lastname
        )

        login(request, new_user)
        return redirect('blog:home')

    return render(request, "register.html")

blogapi/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Jobor Frederick's Blog</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />  
        <!-- Quill CSS -->
        <link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">
        <!-- Quill JS -->
        

    </head>
<body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:home' %}">Frederick's Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}">Home</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:logout' %}">Log Out</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:register' %}">Register</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:contact' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock %}
        
        <footer class="border-top">
                    <div class="container px-4 px-lg-5">
                        <div class="row gx-4 gx-lg-5 justify-content-center">
                            <div class="col-md-10 col-lg-8 col-xl-7">
                                <ul class="list-inline text-center">
                                    <li class="list-inline-item">
                                        <a href="http://www.twitter.com/I_am_FredericK_">
                                            <span class="fa-stack fa-lg">
                                                <i class="fas fa-circle fa-stack-2x"></i>
                                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="https://web.facebook.com/Frederick.Blizz?_rdc=1&_rdr">
                                            <span class="fa-stack fa-lg">
                                                <i class="fas fa-circle fa-stack-2x"></i>
                                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="https://github.com/Jobor-Marho">
                                            <span class="fa-stack fa-lg">
                                                <i class="fas fa-circle fa-stack-2x"></i>
                                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                                <div class="small text-center text-muted fst-italic">Copyright &copy; Jobor Frederick {{ year }}</div>
                            </div>
                        </div>
            </div>
        </footer>
<!-- Bootstrap core JS-->
        <script src="https://cdn.quilljs.com/1.3.7/quill.min.js" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

</body>
</html>

blogapi/templates/edit.html
{% extends 'base.html' %}
    {% block content %}
    <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1484100356142-db6ab6244067?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')"
    id="top">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="page-heading">
                        <h1>Update a Post</h1>
                        <span class="subheading">Edit a Post</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto content">
                    <form action="{% url 'blog:edit' pk=blog.pk %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            <label for="" class="form-label">Title</label>
                            <input type="tezt" name="title" id="" class="form-control" value="{{ title }}">
                        </div>

                        <div class="mt-3">
                            <label for="" class="form-label">Subtitle</label>
                            <input type="text" name="subtitle" id="" class="form-control" value="{{ subtitle }}">
                        </div>

                        <div class="mt-3">
                            <label for="" class="form-label">Image</label>
                            <!-- Display the current image -->
                            {% if img %}
                                <div class="mb-2">
                                    <p>Current Image:</p>
                                    <img src="{{ img }}" alt="Post Image" style="max-width: 300px; height: auto;">
                                </div>
                            {% endif %}
                            <input type="file" name="img" id="" class="form-control">
                        </div>

                        <div class="mt-3">
                            <label for="" class="form-label">Body</label>
                            <textarea name="body" id="editor" class="form-control">{{ body }}</textarea>
                            <p class="text-secondary small fw-light mt-0 fst-italic">Type with html5</p>
                        </div>

                        <div id="editor-container"></div>

                        <div class="text-center mt-3 mb-4"><button class="btn btn-lg btn-primary">Post</button></div>
                    </form>
                </div>
            </div>
        </div>
        <script>
            // Initialize Quill editor
            var quill = new Quill('#editor-container', {
                theme: 'snow'
            });
        
            // Sync Quill's content to the hidden textarea
            var form = document.querySelector('form');
            form.onsubmit = function () {
                var editorContent = document.querySelector('#editor-container .ql-editor').innerHTML;
                document.querySelector('#id_body').value = editorContent;
            };
        </script>
    {% endblock %}

blogapi/templates/error.html
{% block content %}
    <p class="error">500: Sorry, No Internet Connection. Reconnect and try again</p>
{% endblock %}

blogapi/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg'  %})"
    id="top">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Frederick's Blog</h1>
                        <span class="subheading">Get the latest gists</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">

            <div class="col-md-10 col-lg-8 col-xl-7">
                <!-- Post preview-->
                {% if user.pk == 1 and user.is_authenticated %}
                    {% if feed %}
                        {% for gist in feed %}

                            <div class="post-preview">
                                <a href="{% url 'blog:get-post' pk=gist.pk %}">
                                    <h2 class="post-title">{{ gist.title|title }}</h2>
                                    <h3 class="post-subtitle">{{ gist.subtitle }}</h3>
                                </a>
                                <p class="post-meta">
                                    Posted by
                                    <a href="#!">{{ gist.author.username|title }}</a>
                                    on {{ gist.date }}
                                    <a href="{% url 'blog:delete' pk=gist.pk %}">
                                        ✖
                                    </a>
                                </p>
                            </div>
                        {% endfor %}

                        <hr class="my-4" />
                        <!-- Pager-->
                        <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase"
                                                                    href="{% url 'blog:new-post' %}">Create Post →</a>
                        </div>
                    {% else %}
                        <div class="d-flex justify-content-center mb-4"><a class="btn btn-primary text-uppercase"
                                                                    href="{% url 'blog:new-post' %}">Create Post →</a>
                        </div>
                    {% endif %}
                {% else %}
                    {% for gist in feed %}
                        <div class="post-preview">
                            <a href="{% url 'blog:get-post' pk=gist.pk %}">
                                <h2 class="post-title">{{ gist.title |title }}</h2>
                                <h3 class="post-subtitle">{{ gist.subtitle }}</h3>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="{% url 'blog:about' %}">{{ gist.author.username |title }}</a>
                                on {{ gist.date }}
                            </p>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

blogapi/templates/make-post.html
{% extends 'base.html' %}
    {% block content %}
    <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1484100356142-db6ab6244067?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')"
    id="top">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="page-heading">
                        <h1>Create a Post</h1>
                        <span class="subheading">Make a Post</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto content">
                    <form action="{% url 'blog:new-post' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            <label for="" class="form-label">Title</label>
                            <input type="tezt" name="title" id="" class="form-control" value="{{ title }}">
                        </div>

                        <div class="mt-3">
                            <label for="" class="form-label">Subtitle</label>
                            <input type="text" name="subtitle" id="" class="form-control" value="{{ subtitle }}">
                        </div>

                        <div class="mt-3">
                            <label for="" class="form-label">Image</label>
                            <!-- Display the current image -->
                            {% if img %}
                                <div class="mb-2">
                                    <p>Current Image:</p>
                                    <img src="{{ img }}" alt="Post Image" style="max-width: 300px; height: auto;">
                                </div>
                            {% endif %}
                            <input type="file" name="img" id="" class="form-control">
                        </div>

                        <div class="mt-3">
                            <label for="" class="form-label">Body</label>
                            <textarea name="body" id="editor" class="form-control">{{ body }}</textarea>
                            <p class="text-secondary small fw-light mt-0 fst-italic">Type with html5</p>
                        </div>

                        <div id="editor-container"></div>

                        <div class="text-center mt-3 mb-4"><button class="btn btn-lg btn-primary">Post</button></div>
                    </form>
                </div>
            </div>
        </div>
        <script>
            // Initialize Quill editor
            var quill = new Quill('#editor-container', {
                theme: 'snow'
            });
        
            // Sync Quill's content to the hidden textarea
            var form = document.querySelector('form');
            form.onsubmit = function () {
                var editorContent = document.querySelector('#editor-container .ql-editor').innerHTML;
                document.querySelector('#id_body').value = editorContent;
            };
        </script>
    {% endblock %}
    

blogapi/templates/post.html
{% extends 'base.html' %}
{% load static %}

{% load gravatar %}

{% block content %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{ feed.img_url.url }}')" id="top">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{ feed.title|title }}</h1>
                            <h2 class="subheading">{{ feed.subtitle }}</h2>
                            <span class="meta">
                                Posted by
                                <a href="#!">{{ feed.author }}</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>
                            {{ feed.body|safe}}

<!--                            <a href="http://spaceipsum.com/">Space Ipsum</a>-->
<!--                            &middot; Images by-->
<!--                            <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>-->
                        </p>
                        <hr>
                    </div>
                    {% if user.pk == 1 and user.is_authenticated %}
                        <div class="d-flex justify-content-end mb-4">
                            <a class="btn btn-primary text-uppercase" href="{% url 'blog:edit' pk=feed.pk %}">
                                Edit Post
                            </a>
                        </div>
                    {% endif %}



                    <div class="col-md-10 col-lg-8 col-xl-7">
                    <form action="{% url 'blog:get-post' pk=feed.pk %}" method="post">
                            {% csrf_token %}
                        <div>
                            <label for="" class="form-label">Comment</label>
                            <input type="text" name="comment" id="" class="form-control">
                        </div>
                        <div class="mt-3"><button class="btn btn-lg btn-primary">Post</button></div>
                    </form>

                    </div>
                    {% if comments  %}
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <br>
                            
                            <ul class="comments">
                                <p class="fw-bold text-black">Comment Section</p>
                                <li>
                                    {% for comment in comments %}
                                        <div class="avatar">
                                            <img src="{% gravatar_url comment.comment_author.email 40 %}" alt="User Gravatar" />
                                            {{ comment.comment_text|safe }}
                                            <span class="user">posted by <strong>{{ comment.comment_author.username }}</strong>
                                            on {{ comment.date }}
                                            </span>
                                        </div>

                                    {% endfor %}
                                </li>
                            </ul>
                        </div>
                    {% else %}
                    <div class="m-3">
                        <p class="fst-italic text-center lead">No comments yet.</p>
                    </div>
                    {% endif %}

                    </div>
                </div>
            </div>
        </article>

{% endblock %}